const sentences_zh = [
    { sentence: "你好吗？", pinyin: "nǐ hǎo ma?", translation: "How are you?" },
    { sentence: "我喜欢学习中文。", pinyin: "wǒ xǐ huān xué xí zhōng wén.", translation: "I like studying Chinese." },
    { sentence: "今天的天气很好。", pinyin: "jīn tiān de tiān qì hěn hǎo.", translation: "Today's weather is nice." },
    { sentence: "我有一个苹果。", pinyin: "wǒ yǒu yī gè píng guǒ.", translation: "I have an apple." },
    { sentence: "他是我的朋友。", pinyin: "tā shì wǒ de péng yǒu.", translation: "He is my friend." },
    { sentence: "我喜欢吃米饭。", pinyin: "wǒ xǐ huān chī mǐ fàn.", translation: "I like to eat rice." },
    { sentence: "你会说英语吗？", pinyin: "nǐ huì shuō yīng yǔ ma?", translation: "Can you speak English?" },
    { sentence: "她是我的老师。", pinyin: "tā shì wǒ de lǎo shī.", translation: "She is my teacher." },
    { sentence: "我住在北京。", pinyin: "wǒ zhù zài běi jīng.", translation: "I live in Beijing." },
    { sentence: "这个汉字怎么写？", pinyin: "zhè gè hàn zì zěn me xiě?", translation: "How do you write this character?" },
    { sentence: "我有两本书。", pinyin: "wǒ yǒu liǎng běn shū.", translation: "I have two books." },
    { sentence: "他在喝水。", pinyin: "tā zài hē shuǐ.", translation: "He is drinking water." },
    { sentence: "你什么时候去？", pinyin: "nǐ shén me shí hou qù?", translation: "When are you going?" },
    { sentence: "我家有四口人。", pinyin: "wǒ jiā yǒu sì kǒu rén.", translation: "There are four people in my family." },
    { sentence: "我喜欢看电影。", pinyin: "wǒ xǐ huān kàn diàn yǐng.", translation: "I like watching movies." },
    { sentence: "你会写汉字吗？", pinyin: "nǐ huì xiě hàn zì ma?", translation: "Can you write Chinese characters?" },
    { sentence: "他在学校工作。", pinyin: "tā zài xué xiào gōng zuò.", translation: "He works at a school." },
    { sentence: "我喜欢喝茶。", pinyin: "wǒ xǐ huān hē chá.", translation: "I like drinking tea." },
    { sentence: "我们明天见。", pinyin: "wǒ men míng tiān jiàn.", translation: "See you tomorrow." },
    { sentence: "现在几点了？", pinyin: "xiàn zài jǐ diǎn le?", translation: "What time is it now?" },
    { sentence: "我会说一点中文。", pinyin: "wǒ huì shuō yī diǎn zhōng wén.", translation: "I can speak a little Chinese." },
    { sentence: "他今天很忙。", pinyin: "tā jīn tiān hěn máng.", translation: "He is very busy today." },
    { sentence: "这个菜很好吃。", pinyin: "zhè gè cài hěn hǎo chī.", translation: "This dish is delicious." },
    { sentence: "你喜欢什么运动？", pinyin: "nǐ xǐ huān shén me yùn dòng?", translation: "What sport do you like?" },
    { sentence: "他喜欢跑步。", pinyin: "tā xǐ huān pǎo bù.", translation: "He likes running." },
    { sentence: "我每天学习中文。", pinyin: "wǒ měi tiān xué xí zhōng wén.", translation: "I study Chinese every day." },
    { sentence: "我们去吃饭吧。", pinyin: "wǒ men qù chī fàn ba.", translation: "Let's go eat." },
    { sentence: "我今天很高兴。", pinyin: "wǒ jīn tiān hěn gāo xìng.", translation: "I am very happy today." },
    { sentence: "他去商店买东西。", pinyin: "tā qù shāng diàn mǎi dōng xi.", translation: "He went to the store to buy something." },
    { sentence: "你在哪里工作？", pinyin: "nǐ zài nǎ lǐ gōng zuò?", translation: "Where do you work?" },
    { sentence: "今天星期几？", pinyin: "jīn tiān xīng qī jǐ?", translation: "What day is it today?" },
    { sentence: "他喜欢看书。", pinyin: "tā xǐ huān kàn shū.", translation: "He likes reading books." },
    { sentence: "这个苹果很甜。", pinyin: "zhè gè píng guǒ hěn tián.", translation: "This apple is very sweet." },
    { sentence: "我有一个问题。", pinyin: "wǒ yǒu yī gè wèn tí.", translation: "I have a question." },
    { sentence: "他在家里睡觉。", pinyin: "tā zài jiā lǐ shuì jiào.", translation: "He is sleeping at home." },
    { sentence: "你喜欢什么颜色？", pinyin: "nǐ xǐ huān shén me yán sè?", translation: "What color do you like?" },
    { sentence: "她是一个好老师。", pinyin: "tā shì yī gè hǎo lǎo shī.", translation: "She is a good teacher." },
    { sentence: "你会骑自行车吗？", pinyin: "nǐ huì qí zì xíng chē ma?", translation: "Can you ride a bicycle?" },
    { sentence: "我每天早上跑步。", pinyin: "wǒ měi tiān zǎo shàng pǎo bù.", translation: "I run every morning." },
    { sentence: "你喝咖啡还是茶？", pinyin: "nǐ hē kā fēi hái shì chá?", translation: "Do you drink coffee or tea?" },
    { sentence: "他住在上海。", pinyin: "tā zhù zài shàng hǎi.", translation: "He lives in Shanghai." }
];


// const sentences_zh = [
//     { sentence: "你什么时候去机场？", pinyin: "nǐ shén me shí hou qù jī chǎng?", translation: "When are you going to the airport?" },
//     { sentence: "我正在学习中文。", pinyin: "wǒ zhèng zài xué xí zhōng wén.", translation: "I am currently studying Chinese." },
//     { sentence: "他会说一点法语。", pinyin: "tā huì shuō yī diǎn fǎ yǔ.", translation: "He can speak a little French." },
//     { sentence: "我昨天没去上班。", pinyin: "wǒ zuó tiān méi qù shàng bān.", translation: "I didn't go to work yesterday." },
//     { sentence: "这本书很有意思。", pinyin: "zhè běn shū hěn yǒu yì si.", translation: "This book is very interesting." },
//     { sentence: "她想买一件新衣服。", pinyin: "tā xiǎng mǎi yī jiàn xīn yī fu.", translation: "She wants to buy a new piece of clothing." },
//     { sentence: "我们一起去公园散步吧。", pinyin: "wǒ men yī qǐ qù gōng yuán sàn bù ba.", translation: "Let's go for a walk in the park together." },
//     { sentence: "你吃过早饭了吗？", pinyin: "nǐ chī guò zǎo fàn le ma?", translation: "Have you had breakfast?" },
//     { sentence: "她的汉语越来越好了。", pinyin: "tā de hàn yǔ yuè lái yuè hǎo le.", translation: "Her Chinese is getting better and better." },
//     { sentence: "我打算明天去超市。", pinyin: "wǒ dǎ suàn míng tiān qù chāo shì.", translation: "I plan to go to the supermarket tomorrow." },
//     { sentence: "这个问题很简单。", pinyin: "zhè gè wèn tí hěn jiǎn dān.", translation: "This problem is very simple." },
//     { sentence: "我喜欢吃水果和蔬菜。", pinyin: "wǒ xǐ huān chī shuǐ guǒ hé shū cài.", translation: "I like to eat fruits and vegetables." },
//     { sentence: "他们正在看电视。", pinyin: "tā men zhèng zài kàn diàn shì.", translation: "They are watching TV." },
//     { sentence: "我希望你能来我的生日会。", pinyin: "wǒ xī wàng nǐ néng lái wǒ de shēng rì huì.", translation: "I hope you can come to my birthday party." },
//     { sentence: "你怎么去学校？", pinyin: "nǐ zěn me qù xué xiào?", translation: "How do you go to school?" },
//     { sentence: "我觉得这道菜很好吃。", pinyin: "wǒ jué de zhè dào cài hěn hǎo chī.", translation: "I think this dish is very delicious." },
//     { sentence: "她很喜欢小动物。", pinyin: "tā hěn xǐ huān xiǎo dòng wù.", translation: "She really likes small animals." },
//     { sentence: "我们坐出租车去火车站。", pinyin: "wǒ men zuò chū zū chē qù huǒ chē zhàn.", translation: "We take a taxi to the train station." },
//     { sentence: "他每天都锻炼身体。", pinyin: "tā měi tiān dōu duàn liàn shēn tǐ.", translation: "He exercises every day." },
//     { sentence: "她在准备考试。", pinyin: "tā zài zhǔn bèi kǎo shì.", translation: "She is preparing for an exam." },
//     { sentence: "我们下午去看电影。", pinyin: "wǒ men xià wǔ qù kàn diàn yǐng.", translation: "We will go to watch a movie in the afternoon." },
//     { sentence: "我忘记带手机了。", pinyin: "wǒ wàng jì dài shǒu jī le.", translation: "I forgot to bring my phone." },
//     { sentence: "她总是很开心。", pinyin: "tā zǒng shì hěn kāi xīn.", translation: "She is always very happy." },
//     { sentence: "你喜欢什么样的音乐？", pinyin: "nǐ xǐ huān shén me yàng de yīn yuè?", translation: "What kind of music do you like?" },
//     { sentence: "他经常去图书馆学习。", pinyin: "tā jīng cháng qù tú shū guǎn xué xí.", translation: "He often goes to the library to study." },
//     { sentence: "我想要一杯咖啡。", pinyin: "wǒ xiǎng yào yī bēi kā fēi.", translation: "I want a cup of coffee." },
//     { sentence: "这个星期天我很忙。", pinyin: "zhè gè xīng qī tiān wǒ hěn máng.", translation: "I am very busy this Sunday." },
//     { sentence: "她已经离开了学校。", pinyin: "tā yǐ jīng lí kāi le xué xiào.", translation: "She has already left the school." },
//     { sentence: "我喜欢和朋友一起聊天。", pinyin: "wǒ xǐ huān hé péng yǒu yī qǐ liáo tiān.", translation: "I like chatting with friends." },
//     { sentence: "他每天早上都去跑步。", pinyin: "tā měi tiān zǎo shàng dōu qù pǎo bù.", translation: "He goes running every morning." },
//     { sentence: "这家餐厅的菜非常好吃。", pinyin: "zhè jiā cān tīng de cài fēi cháng hǎo chī.", translation: "The food at this restaurant is very delicious." },
//     { sentence: "我们坐地铁去市中心。", pinyin: "wǒ men zuò dì tiě qù shì zhōng xīn.", translation: "We take the subway to the city center." },
//     { sentence: "你明天有空吗？", pinyin: "nǐ míng tiān yǒu kòng ma?", translation: "Are you free tomorrow?" },
//     { sentence: "她正在做作业。", pinyin: "tā zhèng zài zuò zuò yè.", translation: "She is doing her homework." },
//     { sentence: "他去年去了北京。", pinyin: "tā qù nián qù le běi jīng.", translation: "He went to Beijing last year." },
//     { sentence: "我们一起去看电影吧。", pinyin: "wǒ men yī qǐ qù kàn diàn yǐng ba.", translation: "Let's go watch a movie together." },
//     { sentence: "他昨天买了一辆新车。", pinyin: "tā zuó tiān mǎi le yī liàng xīn chē.", translation: "He bought a new car yesterday." },
//     { sentence: "我喜欢在公园里跑步。", pinyin: "wǒ xǐ huān zài gōng yuán lǐ pǎo bù.", translation: "I like running in the park." },
//     { sentence: "这个礼物是给你的。", pinyin: "zhè gè lǐ wù shì gěi nǐ de.", translation: "This gift is for you." },
//     { sentence: "你听过这首歌吗？", pinyin: "nǐ tīng guò zhè shǒu gē ma?", translation: "Have you heard this song?" }
// ];



// const sentences_zh = [
//     { sentence: "你好吗？", translation: "How are you?" },
//     { sentence: "我喜欢学习中文。", translation: "I like studying Chinese." },
//     { sentence: "今天的天气很好。", translation: "Today's weather is nice." },
//     // Add more sentences as needed
// ];