const sentences_nl = [
    { sentence: "Hij probeert elke dag minstens tien pagina's in het Nederlands te lezen.", translation: "He tries to read at least ten pages in Dutch every day." },
    { sentence: "Ze heeft besloten om een cursus Nederlands te volgen om haar vaardigheden te verbeteren.", translation: "She has decided to take a Dutch course to improve her skills." },
    { sentence: "Het weer in Nederland kan snel veranderen, dus het is belangrijk om voorbereid te zijn.", translation: "The weather in the Netherlands can change quickly, so it's important to be prepared." },
    { sentence: "De trein vertrekt elke ochtend om acht uur vanaf het centraal station.", translation: "The train departs every morning at eight o'clock from the central station." },
    { sentence: "Hij heeft moeite om de grammatica van de Nederlandse taal onder de knie te krijgen.", translation: "He struggles to master the grammar of the Dutch language." },
    { sentence: "Ze houden van fietsen langs de kanalen, vooral in de lente als de bloemen in bloei staan.", translation: "They love cycling along the canals, especially in spring when the flowers are in bloom." },
    { sentence: "Het is belangrijk om de cultuur van een land te begrijpen als je de taal leert.", translation: "It is important to understand the culture of a country when learning the language." },
    { sentence: "De winkels sluiten vroeg op zondag, dus je moet ervoor zorgen dat je op tijd je boodschappen doet.", translation: "The stores close early on Sunday, so you need to make sure you do your shopping on time." },
    { sentence: "Hij heeft een nieuwe baan gevonden en begint volgende week met werken.", translation: "He has found a new job and starts working next week." },
    { sentence: "Ze genieten van het bezoeken van musea en het ontdekken van nieuwe kunstwerken.", translation: "They enjoy visiting museums and discovering new artworks." },
    { sentence: "Het leren van een nieuwe taal kan uitdagend zijn, maar het is ook zeer lonend.", translation: "Learning a new language can be challenging, but it is also very rewarding." },
    { sentence: "Ze heeft de gewoonte om elke ochtend naar het nieuws te luisteren om op de hoogte te blijven.", translation: "She has the habit of listening to the news every morning to stay informed." },
    { sentence: "Zijn vriendelijkheid en geduld maken hem een uitstekende leraar.", translation: "His kindness and patience make him an excellent teacher." },
    { sentence: "Ze plannen om deze zomer een roadtrip door Europa te maken.", translation: "They are planning to take a road trip through Europe this summer." },
    { sentence: "Hij is altijd bereid om anderen te helpen, zelfs als hij het druk heeft.", translation: "He is always willing to help others, even when he is busy." },
    { sentence: "Ze kijkt uit naar het feest van vanavond, waar ze al haar vrienden weer zal zien.", translation: "She is looking forward to tonight's party, where she will see all her friends again." },
    { sentence: "Het huis dat ze willen kopen, ligt in een rustige buurt met veel groen.", translation: "The house they want to buy is located in a quiet neighborhood with lots of greenery." },
    { sentence: "Hij probeert elke dag een beetje te oefenen, omdat hij zijn Nederlands wil verbeteren.", translation: "He tries to practice a little every day because he wants to improve his Dutch." },
    { sentence: "Ze hebben besloten om hun vakantie in Nederland door te brengen om meer van het land te zien.", translation: "They have decided to spend their vacation in the Netherlands to see more of the country." },
    { sentence: "Hij vindt het moeilijk om Nederlandse boeken te lezen zonder een woordenboek erbij te gebruiken.", translation: "He finds it difficult to read Dutch books without using a dictionary." },
    { sentence: "Ze zijn van plan om volgend jaar naar een Nederlands sprekend land te verhuizen.", translation: "They plan to move to a Dutch-speaking country next year." },
    { sentence: "Hij houdt van koken en probeert vaak nieuwe recepten uit de Nederlandse keuken.", translation: "He loves cooking and often tries new recipes from Dutch cuisine." },
    { sentence: "Het leren van nieuwe woorden en zinnen helpt hem om zelfverzekerder te spreken.", translation: "Learning new words and phrases helps him speak with more confidence." },
    { sentence: "Ze heeft een intensieve cursus gevolgd om haar spreekvaardigheid in het Nederlands te verbeteren.", translation: "She took an intensive course to improve her speaking skills in Dutch." },
    { sentence: "Zijn doel is om vloeiend Nederlands te spreken tegen het einde van het jaar.", translation: "His goal is to speak Dutch fluently by the end of the year." },
    { sentence: "Ze vindt het leuk om Nederlandse films te kijken om haar luistervaardigheid te oefenen.", translation: "She enjoys watching Dutch movies to practice her listening skills." },
    { sentence: "Het is belangrijk om regelmatig te oefenen als je een nieuwe taal leert.", translation: "It is important to practice regularly when learning a new language." },
    { sentence: "Hij heeft zijn studie afgerond en is nu op zoek naar een baan in Nederland.", translation: "He has completed his studies and is now looking for a job in the Netherlands." },
    { sentence: "Ze vindt het uitdagend om de juiste uitspraak in het Nederlands onder de knie te krijgen.", translation: "She finds it challenging to master the correct pronunciation in Dutch." },
    { sentence: "Ze hebben een abonnement genomen op een Nederlandse krant om hun leesvaardigheid te verbeteren.", translation: "They have subscribed to a Dutch newspaper to improve their reading skills." },
    { sentence: "Hij heeft veel Nederlandse vrienden gemaakt sinds hij hier is komen wonen.", translation: "He has made many Dutch friends since he moved here." },
    { sentence: "Ze bezochten verschillende Nederlandse steden om meer te leren over de cultuur en geschiedenis.", translation: "They visited several Dutch cities to learn more about the culture and history." },
    { sentence: "Het is handig om de taal van het land te spreken waar je woont.", translation: "It is useful to speak the language of the country where you live." },
    { sentence: "Ze vinden het leuk om Nederlandse muziek te luisteren en mee te zingen.", translation: "They enjoy listening to Dutch music and singing along." },
    { sentence: "Hij heeft zijn woordenschat uitgebreid door dagelijks nieuwe woorden te leren.", translation: "He has expanded his vocabulary by learning new words daily." },
    { sentence: "Ze waren verrast door de schoonheid van de Nederlandse landschappen tijdens hun reis.", translation: "They were surprised by the beauty of the Dutch landscapes during their trip." },
    { sentence: "Het kostte hem veel moeite om de regels van de Nederlandse grammatica te begrijpen.", translation: "It took him a lot of effort to understand the rules of Dutch grammar." },
    { sentence: "Ze proberen elke week een nieuwe Nederlandse film of serie te kijken.", translation: "They try to watch a new Dutch movie or series every week." },
    { sentence: "Hij heeft zijn familie uitgenodigd om hem te bezoeken in Nederland.", translation: "He invited his family to visit him in the Netherlands." },
    { sentence: "Ze houden van het eten van typisch Nederlandse gerechten zoals stamppot en pannenkoeken.", translation: "They love eating typical Dutch dishes like stamppot and pancakes." },
    { sentence: "De vergaderingen worden elke maandag om negen uur 's ochtends gehouden.", translation: "The meetings are held every Monday at nine in the morning." },
    { sentence: "Ze heeft een indrukwekkend portfolio opgebouwd door de jaren heen.", translation: "She has built an impressive portfolio over the years." },
    { sentence: "Het team werkt hard om de deadline voor het project te halen.", translation: "The team is working hard to meet the project deadline." },
    { sentence: "Hij geniet van de stilte van de ochtend voordat de stad tot leven komt.", translation: "He enjoys the quiet of the morning before the city comes to life." },
    { sentence: "Ze heeft moeite om een balans te vinden tussen werk en privéleven.", translation: "She struggles to find a balance between work and private life." },
    { sentence: "Het is cruciaal om goed voorbereid te zijn voor de presentatie van morgen.", translation: "It is crucial to be well-prepared for tomorrow's presentation." },
    { sentence: "Ze hebben besloten om hun vakantie in een ander land door te brengen dit jaar.", translation: "They have decided to spend their vacation in another country this year." },
    { sentence: "Hij probeert zijn tijd beter te beheren door gebruik te maken van een agenda.", translation: "He tries to manage his time better by using a planner." },
    { sentence: "De nieuwe medewerker heeft snel geleerd hoe de systemen werken.", translation: "The new employee quickly learned how the systems work." },
    { sentence: "Ze waarderen het dat hun baas altijd openstaat voor suggesties.", translation: "They appreciate that their boss is always open to suggestions." },
    { sentence: "Het bedrijf heeft aangekondigd dat ze volgend jaar willen uitbreiden.", translation: "The company has announced that they want to expand next year." },
    { sentence: "Hij is vastbesloten om zijn doelen te bereiken, ongeacht de obstakels.", translation: "He is determined to achieve his goals, regardless of the obstacles." },
    { sentence: "Ze genieten van het verkennen van onbekende delen van de stad in hun vrije tijd.", translation: "They enjoy exploring unfamiliar parts of the city in their free time." },
    { sentence: "De samenwerking tussen de afdelingen heeft geleid tot betere resultaten.", translation: "The collaboration between the departments has led to better results." },
    { sentence: "Hij is een expert in zijn vakgebied en wordt vaak om advies gevraagd.", translation: "He is an expert in his field and is often asked for advice." },
    { sentence: "Ze hebben de nodige stappen ondernomen om hun productiviteit te verhogen.", translation: "They have taken the necessary steps to increase their productivity." },
    { sentence: "Het is belangrijk om regelmatig feedback te geven aan je teamleden.", translation: "It is important to regularly give feedback to your team members." },
    { sentence: "Ze plannen een grote feest voor hun vijftigste huwelijksverjaardag.", translation: "They are planning a big party for their fiftieth wedding anniversary." },
    { sentence: "Hij heeft onlangs een boek gepubliceerd dat veel lof heeft gekregen.", translation: "He recently published a book that has received much praise." },
    { sentence: "De manager benadrukte het belang van het volgen van de richtlijnen.", translation: "The manager emphasized the importance of following the guidelines." },
    { sentence: "Ze zijn van plan om hun huis te renoveren voordat ze het te koop aanbieden.", translation: "They plan to renovate their house before putting it up for sale." },
    { sentence: "Hij heeft een passie voor technologie en volgt altijd de laatste trends.", translation: "He has a passion for technology and always follows the latest trends." },
    { sentence: "Ze hebben een nieuwe strategie ontwikkeld om hun verkoopcijfers te verbeteren.", translation: "They have developed a new strategy to improve their sales figures." },
    { sentence: "Het is essentieel om een noodplan te hebben voor onverwachte situaties.", translation: "It is essential to have a contingency plan for unexpected situations." },
    { sentence: "Hij heeft veel tijd geïnvesteerd in het opzetten van zijn eigen bedrijf.", translation: "He has invested a lot of time in setting up his own business." },
    { sentence: "Ze bewonderen zijn toewijding aan het verbeteren van zijn vaardigheden.", translation: "They admire his dedication to improving his skills." },
    { sentence: "Het is een uitdaging om met verschillende culturen samen te werken, maar het is ook verrijkend.", translation: "It is challenging to work with different cultures, but it is also enriching." },
    { sentence: "Hij heeft ervoor gekozen om een sabbatical te nemen om zich op zijn persoonlijke doelen te concentreren.", translation: "He has chosen to take a sabbatical to focus on his personal goals." },
    { sentence: "Ze hebben hun zinnen gezet op het winnen van de internationale competitie.", translation: "They have set their sights on winning the international competition." },
    { sentence: "Het bedrijf biedt regelmatig trainingen aan om de vaardigheden van medewerkers te verbeteren.", translation: "The company regularly offers training to improve employees' skills." },
    { sentence: "Hij is trots op wat hij tot nu toe heeft bereikt in zijn carrière.", translation: "He is proud of what he has achieved in his career so far." },
    { sentence: "Ze hebben een uitgebreide analyse uitgevoerd om de marktkansen te beoordelen.", translation: "They conducted a thorough analysis to assess market opportunities." },
    { sentence: "Het is belangrijk om duidelijke doelen te stellen voor het komende jaar.", translation: "It is important to set clear goals for the coming year." },
    { sentence: "Hij geniet van het werken aan projecten die zijn creativiteit uitdagen.", translation: "He enjoys working on projects that challenge his creativity." },
    { sentence: "Ze hebben besloten om samen een nieuw avontuur aan te gaan en naar het buitenland te verhuizen.", translation: "They have decided to embark on a new adventure together and move abroad." },
    { sentence: "Het is essentieel om regelmatig pauzes te nemen om je energie op peil te houden.", translation: "It is essential to take regular breaks to maintain your energy levels." },
    { sentence: "Hij heeft geleerd hoe belangrijk het is om effectief te communiceren met zijn team.", translation: "He has learned how important it is to communicate effectively with his team." },
    { sentence: "Ze waren onder de indruk van zijn presentatie tijdens de conferentie.", translation: "They were impressed by his presentation at the conference." },
    { sentence: "Het is een goede gewoonte om aan het einde van de dag je takenlijst bij te werken.", translation: "It is a good habit to update your task list at the end of the day." },
    { sentence: "Hij heeft zijn zinnen gezet op het leren van een nieuwe taal dit jaar.", translation: "He is determined to learn a new language this year." },
    { sentence: "Ze hebben hard gewerkt om hun doelen te bereiken en het was de moeite waard.", translation: "They worked hard to achieve their goals, and it was worth it." }
];
