const sentences_fr = [
    { sentence: "Le chat noir est sur le toit.", translation: "The black cat is on the roof." },
    { sentence: "La souris grise est dans la maison.", translation: "The gray mouse is in the house." },
    { sentence: "Le chien brun court dans le parc.", translation: "The brown dog runs in the park." },
    { sentence: "L'oiseau bleu chante dans l'arbre.", translation: "The blue bird sings in the tree." },
    { sentence: "Le soleil brille sur la plage.", translation: "The sun shines on the beach." },
    { sentence: "La lune est pleine ce soir.", translation: "The moon is full tonight." },
    { sentence: "Les étoiles brillent dans le ciel.", translation: "The stars are shining in the sky." },
    { sentence: "Le vent souffle fort aujourd'hui.", translation: "The wind is blowing strong today." },
    { sentence: "La pluie tombe doucement.", translation: "The rain is falling softly." },
    { sentence: "La neige recouvre les montagnes.", translation: "The snow covers the mountains." },
    { sentence: "Le printemps arrive avec des fleurs.", translation: "Spring arrives with flowers." },
    { sentence: "Les oiseaux migrent vers le sud en hiver.", translation: "The birds migrate south in the winter." },
    { sentence: "L'automne est la saison des feuilles mortes.", translation: "Autumn is the season of falling leaves." },
    { sentence: "La mer est calme aujourd'hui.", translation: "The sea is calm today." },
    { sentence: "Le bateau navigue sur l'océan.", translation: "The boat sails on the ocean." },
    { sentence: "Le poisson nage dans le lac.", translation: "The fish swims in the lake." },
    { sentence: "La rivière coule à travers la vallée.", translation: "The river flows through the valley." },
    { sentence: "Le volcan est en éruption.", translation: "The volcano is erupting." },
    { sentence: "La montagne est couverte de neige.", translation: "The mountain is covered in snow." },
    { sentence: "Le désert est chaud et sec.", translation: "The desert is hot and dry." },
    { sentence: "La forêt est dense et sombre.", translation: "The forest is dense and dark." },
    { sentence: "Le lion est le roi de la savane.", translation: "The lion is the king of the savannah." },
    { sentence: "L'éléphant marche lentement.", translation: "The elephant walks slowly." },
    { sentence: "Le singe grimpe aux arbres.", translation: "The monkey climbs trees." },
    { sentence: "Le tigre chasse dans la jungle.", translation: "The tiger hunts in the jungle." },
    { sentence: "La girafe a un long cou.", translation: "The giraffe has a long neck." },
    { sentence: "Le zèbre a des rayures noires et blanches.", translation: "The zebra has black and white stripes." },
    { sentence: "Le panda mange du bambou.", translation: "The panda eats bamboo." },
    { sentence: "Le kangourou saute dans le désert australien.", translation: "The kangaroo hops in the Australian desert." },
    { sentence: "Le renard est rusé et rapide.", translation: "The fox is cunning and fast." },
    { sentence: "L'ours hiberne pendant l'hiver.", translation: "The bear hibernates during the winter." },
    { sentence: "Le cheval court à travers les champs.", translation: "The horse runs across the fields." },
    { sentence: "Le serpent glisse sur le sol.", translation: "The snake slithers on the ground." },
    { sentence: "La tortue avance lentement mais sûrement.", translation: "The turtle moves slowly but surely." },
    { sentence: "Le papillon vole de fleur en fleur.", translation: "The butterfly flies from flower to flower." },
    { sentence: "L'abeille butine le nectar des fleurs.", translation: "The bee gathers nectar from flowers." },
    { sentence: "La coccinelle est un insecte rouge avec des points noirs.", translation: "The ladybug is a red insect with black spots." },
    { sentence: "Le requin nage dans les profondeurs de l'océan.", translation: "The shark swims in the depths of the ocean." },
    { sentence: "Le dauphin saute hors de l'eau.", translation: "The dolphin jumps out of the water." },
    { sentence: "Le phoque se repose sur la glace.", translation: "The seal rests on the ice." },
    { sentence: "Le manchot marche en groupe sur la banquise.", translation: "The penguin walks in groups on the ice floe." },
    { sentence: "La bibliothèque est pleine de livres intéressants.", translation: "The library is full of interesting books." },
    { sentence: "Le marché est animé le samedi matin.", translation: "The market is lively on Saturday mornings." },
    { sentence: "Le peintre a créé une œuvre magnifique.", translation: "The painter created a magnificent work." },
    { sentence: "Les enfants rient et jouent dans la cour.", translation: "The children laugh and play in the yard." },
    { sentence: "Le boulanger prépare du pain frais chaque jour.", translation: "The baker prepares fresh bread every day." },
    { sentence: "La cloche de l'église sonne toutes les heures.", translation: "The church bell rings every hour." },
    { sentence: "Les lumières de la ville s'allument au crépuscule.", translation: "The city lights turn on at dusk." },
    { sentence: "Le fermier nourrit les animaux le matin.", translation: "The farmer feeds the animals in the morning." },
    { sentence: "Le joueur de football marque un but incroyable.", translation: "The football player scores an incredible goal." },
    { sentence: "Le professeur explique la leçon avec patience.", translation: "The teacher explains the lesson with patience." },
    { sentence: "Les touristes visitent le musée chaque été.", translation: "Tourists visit the museum every summer." },
    { sentence: "Le médecin examine le patient avec soin.", translation: "The doctor examines the patient carefully." },
    { sentence: "Le mécanicien répare la voiture dans le garage.", translation: "The mechanic repairs the car in the garage." },
    { sentence: "La rivière traverse le village pittoresque.", translation: "The river runs through the picturesque village." },
    { sentence: "La soupe chaude est parfaite pour une journée froide.", translation: "Hot soup is perfect for a cold day." },
    { sentence: "Le château médiéval se dresse au sommet de la colline.", translation: "The medieval castle stands on top of the hill." },
    { sentence: "Le pêcheur attend patiemment que le poisson morde.", translation: "The fisherman waits patiently for the fish to bite." },
    { sentence: "La montagne offre une vue imprenable sur la vallée.", translation: "The mountain offers a breathtaking view of the valley." },
    { sentence: "La plage est bordée de palmiers majestueux.", translation: "The beach is lined with majestic palm trees." },
    { sentence: "Le musicien joue une mélodie douce au piano.", translation: "The musician plays a soft melody on the piano." },
    { sentence: "Le parfum des fleurs remplit l'air du jardin.", translation: "The scent of flowers fills the garden air." },
    { sentence: "Le chat se prélasse au soleil sur le rebord de la fenêtre.", translation: "The cat lounges in the sun on the windowsill." },
    { sentence: "Le vent souffle à travers les branches des arbres.", translation: "The wind blows through the branches of the trees." },
    { sentence: "La lampe éclaire doucement la pièce.", translation: "The lamp softly lights the room." },
    { sentence: "Les feuilles de thé infusent dans l'eau chaude.", translation: "The tea leaves steep in hot water." },
    { sentence: "Le sentier mène à une clairière dans la forêt.", translation: "The path leads to a clearing in the forest." },
    { sentence: "La montagne est couverte de brouillard ce matin.", translation: "The mountain is covered in fog this morning." },
    { sentence: "Les écoliers portent des cartables lourds.", translation: "The schoolchildren carry heavy backpacks." },
    { sentence: "La bicyclette rouge est appuyée contre le mur.", translation: "The red bicycle is leaning against the wall." },
    { sentence: "Le violoniste joue une symphonie émouvante.", translation: "The violinist plays a moving symphony." },
    { sentence: "Le café au coin de la rue est toujours plein.", translation: "The café on the corner is always full." },
    { sentence: "La montre ancienne a une belle gravure.", translation: "The antique watch has a beautiful engraving." },
    { sentence: "Les enfants dessinent des figures sur le trottoir.", translation: "The children draw figures on the sidewalk." },
    { sentence: "Le pont en pierre traverse la rivière paisible.", translation: "The stone bridge crosses the peaceful river." },
    { sentence: "Les livres sont soigneusement rangés sur les étagères.", translation: "The books are neatly arranged on the shelves." },
    { sentence: "Le vieux moulin tourne lentement dans le vent.", translation: "The old mill slowly turns in the wind." },
    { sentence: "Le pot de fleurs est posé sur la table du jardin.", translation: "The flower pot is placed on the garden table." },
    { sentence: "Les nuages se déplacent rapidement dans le ciel.", translation: "The clouds move quickly across the sky." },
    { sentence: "Le chemin de fer traverse la campagne verte.", translation: "The railway crosses the green countryside." },
    { sentence: "Le chien aboie joyeusement en voyant son maître.", translation: "The dog barks joyfully at seeing its owner." },
    { sentence: "Le feuillage d'automne est magnifique cette année.", translation: "The autumn foliage is beautiful this year." },
];

